[project]
name = "agentic-ai"
requires-python = ">=3.11,<3.13"
version = "0.1.0"
description = "agentic AI course repo"
authors = [
    {name = "devnaveedsarwar",email = "learnwithnaveedsarwar@gmail.com"}
]
readme = "README.md"
dependencies = [
    "crewai[tools]>=0.100.1,<0.101.0",
    "langchain-community>=0.3.16",
    "langchain>=0.3.17,<0.4.0",
    "langchain-core>=0.3.33,<0.4.0",
    "langchain-openai>=0.2.14",
    "python-dotenv>=1.0.1",
    "langchain-google-genai>=2.0.9",
    "fastapi>=0.115.8",
    "uvicorn>=0.34.0",
    "pymongo>=4.11",
    "langgraph>=0.2.69",
    "streamlit>=1.41.1",
    "python-multipart>=0.0.20",
    "crewai-tools>=0.33.0",
    "alembic>=1.14.1",
    "psycopg2-binary>=2.9.10",
<<<<<<< HEAD
    "docling>=2.25.0",
=======
    "pyjwt>=2.10.1",
    "passlib>=1.7.4",
>>>>>>> 1b405d5397f488199aad24e0f51c1b3c2b06580c
]
