[project]
name = "customer-support-agent-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai-agents>=0.0.11",
    "pinecone>=7.0.1",
    "pyreadline3>=3.5.4",
]
